# -*- coding: utf-8 -*-
import sys

sys.stdout.reconfigure(encoding='utf-8')

file_path = r'c:\Users\User\OneDrive\Desktop\Dashboard\src\Scripts.html'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. New keys to add
new_keys = {
    'home.am.totalRev': { 'th': 'Rev รวม', 'en': 'Total Rev' },
    'home.am.totalVol': { 'th': 'Vol รวม', 'en': 'Total Vol' },
    'home.am.perAgent': { 'th': 'ต่อ agent', 'en': 'per agent' },
    'home.am.pcsPerAgent': { 'th': 'ชิ้น/agent', 'en': 'pcs/agent' },
    'home.status.needsImprovement': { 'th': 'ต้องเร่งแก้ไข', 'en': 'Urgent Action' },
    'home.status.followup': { 'th': 'ติดตาม', 'en': 'Follow Up' },
    'home.status.normal': { 'th': 'ปกติ', 'en': 'Normal' },
    'home.status.inactive': { 'th': 'หยุดนิ่ง', 'en': 'Inactive' },
    'home.status.growth': { 'th': 'เติบโต', 'en': 'Growth' },
    'home.pctTarget': { 'th': '% เป้า', 'en': '% Target' },
    'home.am.comparePrevMonth': { 'th': 'เปรียบเทียบกับเดือนก่อนหน้า', 'en': 'Compare with previous month' },
    'home.am.byZone': { 'th': ' — แบ่งตาม Zone', 'en': ' — by Zone' },
    'home.am.momByZone': { 'th': 'MoM แต่ละ Zone', 'en': 'MoM by Zone' },
    'trend.growth': { 'th': '🚀 เติบโต', 'en': '🚀 Growth' },
    'trend.improving': { 'th': '📈 ดีขึ้น', 'en': '📈 Improving' },
    'trend.declining': { 'th': '📉 ลดลง', 'en': '📉 Declining' },
    'trend.risk': { 'th': '⚠️ เสี่ยง', 'en': '⚠️ Risk' }
}

dict_lines = []
for k, v in new_keys.items():
    th_val = v["th"].replace("'", "\\'")
    en_val = v["en"].replace("'", "\\'")
    dict_lines.append(f"    '{k}': {{ th: '{th_val}', en: '{en_val}' }},")

dict_block = "\n".join(dict_lines)
target_dict_end = "'home.noRevenueThisMonth': { th: 'ไม่มีรายได้เดือนนี้', en: 'No revenue this month' },"

if target_dict_end in content:
    replacement = target_dict_end + ",\n" + dict_block
    content = content.replace(target_dict_end, replacement)
    print("SUCCESS: Extended APP_I18N dictionary.")
else:
    print("ERROR: Could not find target_dict_end in Scripts.html.")
    sys.exit(1)

# Canonicalize
def clean_str(s):
    return s.replace('\r\n', '\n')

content_clean = clean_str(content)

# 2. Replacements in active AM dashboard
am_stats_replacements = [
    ("am-stat-lbl\" style=\"color:#166534\">เติบโต</div>", "am-stat-lbl\" style=\"color:#166534\">' + t('home.status.growth') + '</div>"),
    ("am-stat-lbl\" style=\"color:#0369a1\">Rev รวม</div>", "am-stat-lbl\" style=\"color:#0369a1\">' + t('home.am.totalRev') + '</div>"),
    ("am-stat-lbl\" style=\"color:#0f766e\">Vol รวม</div>", "am-stat-lbl\" style=\"color:#0f766e\">' + t('home.am.totalVol') + '</div>"),
    ("color:var(--t2);margin-top:1px\">ต่อ agent</div>", "color:var(--t2);margin-top:1px\">' + t('home.am.perAgent') + '</div>"),
    ("color:var(--t2);margin-top:1px\">ชิ้น/agent</div>", "color:var(--t2);margin-top:1px\">' + t('home.am.pcsPerAgent') + '</div>"),
    ("padding:2px 8px;border-radius:20px;font-weight:700\">ต้องเร่งแก้ไข</span>", "padding:2px 8px;border-radius:20px;font-weight:700\">' + t('home.status.needsImprovement') + '</span>"),
    ("padding:2px 8px;border-radius:20px;font-weight:700\">ติดตาม</span>", "padding:2px 8px;border-radius:20px;font-weight:700\">' + t('home.status.followup') + '</span>"),
    ("padding:2px 8px;border-radius:20px;font-weight:700\">ปกติ</span>", "padding:2px 8px;border-radius:20px;font-weight:700\">' + t('home.status.normal') + '</span>"),
    ("color:var(--t2);margin-top:1px\">' + z.leads.toLocaleString() + ' agents</div>", "color:var(--t2);margin-top:1px\">' + z.leads.toLocaleString() + ' \' + t(\'label.agentsUnit\') + \'</div>"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents</div>", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\') + \'"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">' + z.leads.toLocaleString() + ' agents", "color:var(--t2);margin-top:1px\">' + z.leads.toLocaleString() + ' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">' + z.leads.toLocaleString() + ' agents", "color:var(--t2);margin-top:1px\">' + z.leads.toLocaleString() + ' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' agents", "color:var(--t2);margin-top:1px\">\' + z.leads.toLocaleString() + \' \' + t('label.agentsUnit') + '</div>"),
    ("color:var(--t2);margin-top:1px\">' + z.leads.toLocaleString() + ' agents</div>", "color:var(--t2);margin-top:1px\">' + z.leads.toLocaleString() + ' \' + t('label.agentsUnit') + '</div>"),
    ("color:var(--t2);margin-top:1px\">\' + stagnant + \' agents", "color:var(--t2);margin-top:1px\">\' + stagnant + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">' + stagnant + ' agents", "color:var(--t2);margin-top:1px\">' + stagnant + ' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">\' + (stagnant || 0) + \' agents", "color:var(--t2);margin-top:1px\">\' + (stagnant || 0) + \' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">' + (stagnant || 0) + ' agents", "color:var(--t2);margin-top:1px\">' + (stagnant || 0) + ' \' + t(\'label.agentsUnit\')"),
    ("color:var(--t2);margin-top:1px\">' + stagnant + ' agents</div>", "color:var(--t2);margin-top:1px\">' + stagnant + ' \' + t('label.agentsUnit') + '</div>"),
    ("color:var(--t2);margin-top:1px\">\' + stagnant + \' agents</div>", "color:var(--t2);margin-top:1px\">\' + stagnant + \' \' + t(\'label.agentsUnit\') + \'</div>"),
    ("color:var(--t2);white-space:nowrap\">% เป้า</div>", "color:var(--t2);white-space:nowrap\">' + t('home.pctTarget') + '</div>"),
    ("_amSecHdr('📅', 'เปรียบเทียบกับเดือนก่อนหน้า', m.th + ' vs ' + mp.th + ' — แบ่งตาม Zone'",
     "_amSecHdr('📅', t('home.am.comparePrevMonth'), (appLang() === 'th' ? m.th : m.en) + ' vs ' + (appLang() === 'th' ? mp.th : mp.en) + t('home.am.byZone')"),
    ("div style=\"font-size:10px;font-weight:700;color:var(--t2);text-transform:uppercase;margin-bottom:7px\">MoM แต่ละ Zone</div>",
     "div style=\"font-size:10px;font-weight:700;color:var(--t2);text-transform:uppercase;margin-bottom:7px\">' + t('home.am.momByZone') + '</div>"),
    ("🚀 เติบโต", "' + t('trend.growth') + '"),
    ("📈 ดีขึ้น", "' + t('trend.improving') + '"),
    ("📉 ลดลง", "' + t('trend.declining') + '"),
    ("⚠️ เสี่ยง", "' + t('trend.risk') + '")
]

replaced_count = 0
for target, replacement in am_stats_replacements:
    target_clean = clean_str(target)
    replacement_clean = clean_str(replacement)
    if target_clean in content_clean:
        content_clean = content_clean.replace(target_clean, replacement_clean)
        replaced_count += 1
    else:
        # Try a substring or simple quote variant if needed
        pass

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content_clean)

print(f"SUCCESS: Replaced {replaced_count} out of {len(am_stats_replacements)} AM stats strings.")
